### ISSUE TITLE
Los datos númericos son tomados '' por default

### ISSUE THREAD

**Issue by JuanGamezSW** [swsapien/pycfdi-transform#8]
Cuando algún atributo numérico no aparece dentro del XML esté se arroja como "". Creo que para sistemas que dependan de un dato numérico sería mejor que saliera como "0.00".

**Comment by hermesjimenez** [comment]
No se si aplique para todos los casos. Por ejemplo el atributo TipoCambio si ponemos 0.00 teoricamente cuando no lo declaras es porque la moneda es MXN y el tipo de cambio es 1.00

**Comment by hermesjimenez** [comment]
se aprueba para trabajarlo , solo considerando los valores por default especiales como el TipoCambio

**Comment by hermesjimenez** [comment]
en la implementación 0.1.2.12rc1 se agrega propiedades de configuración para definir como tratar los valores numericos.
